--- #YAML:1.0
name:                     Test-YAML-Meta
version:                  0.12
abstract:                 A test module to validate a META.yml file.
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Test::YAML::Valid:      0.03
  Test::More:             0.70
  Test::Builder:          0
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::YAML::Valid:      0.03
  YAML:                   0
  YAML::Syck:             0
build_requires:
  Test::More:             0.70
  Test::Builder::Tester:  0

provides:
  Test::YAML::Meta:
    file:     lib/Test/YAML/Meta.pm
    version:  0.12
  Test::YAML::Meta::Version:
    file:     lib/Test/YAML/Meta/Version.pm
    version:  0.12
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-YAML-Meta

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
